[package]
name = "hyprland-relative-workspace"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hyprland-relative-workspace"

[dependencies]
hyprland = "0.3.1"
