# Maintainer: CheesyPhoenix
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=hyprland-relative-workspace-bin
pkgver=1.1.7
pkgrel=1
pkgdesc="A tool to switch Hyprland workspaces relatively to monitor"
url="https://github.com/CheesyPhoenix/hyprland-relative-workspace"
license=("MIT")
arch=("x86_64")
provides=("hyprland-relative-workspace")
conflicts=("hyprland-relative-workspace")
source=("https://github.com/CheesyPhoenix/hyprland-relative-workspace/releases/download/v$pkgver/hyprland-relative-workspace-$pkgver-x86_64.tar.gz")
sha256sums=("6baecef688a5c56d20e607a647931675eed49971c23567087c859cc4d2f9e6ad")

package() {
    install -Dm755 hyprland-relative-workspace -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
